# Generated by Django 2.2.5 on 2019-10-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nichos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predio',
            name='propietario',
        ),
        migrations.AlterField(
            model_name='predio',
            name='nomenclatura',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='ornato',
            field=models.BooleanField(),
        ),
    ]
