# Generated by Django 2.2.5 on 2019-10-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nichos', '0002_auto_20191004_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=250)),
                ('espacios', models.IntegerField()),
                ('niveles', models.IntegerField()),
                ('ornato', models.BooleanField()),
                ('cancelado', models.BooleanField()),
                ('inspeccion', models.BooleanField()),
                ('fecha', models.DateField()),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nichos.Predio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nichos.Propietario')),
            ],
        ),
        migrations.DeleteModel(
            name='owner',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='predio',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='propietario',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='reservacion',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
